### ISSUE TITLE
No graphs for virtual sensors

### ISSUE THREAD

**Issue by Mediacj** [empierre/MyDomoAtHome#17]
I Installed MDAH but only one thing isn't working for me the graphs of the temperature sensors are not displayed, when I press a temperature sensor I get the error: No graph data to display

The graphs of a windmeter and solarpanels are showing up perfectly.

It are virtual temperature/humidity sensors but the windmeter and solarpanel are also virtual.

System:
Domoticz version: 2.2903
Latest MDAH version
Raspberry 2

**Comment by empierre** [comment]
Issue raised to Imperihome Team  #3474

**Comment by empierre** [comment]
Should be fixed from yesterday's late night commit, please update and report if this os ok

**Comment by empierre** [comment]
not ax external bug, fixed yesterday

**Comment by empierre** [comment]
close

**Comment by Mediacj** [comment]
I tested it but it didn't solve the problem for me, since yesterday I also have a Rfxcom and also the TH sensors of Rfxcom don't display the graph.

**Comment by empierre** [comment]
do you have the graph in Domoticz for iun dev version there is a regression
and some graphes don't have values anymore...

**Comment by Mediacj** [comment]
Yes in Domoticz the graphs are fine(beta version)

You mean "ios" for "iun" I suppose, ok then I have to wait. 

Thanks anyway!

**Comment by empierre** [comment]
Hello,

  the graphes are back in the last version from domoticz, hard time to
build on something not stabilized...

**Comment by empierre** [comment]
did I had you database ?

**Comment by Mediacj** [comment]
No but the problem is solved, I don't know how but today the graphs show up :)

So case closed thanks again!

**Comment by empierre** [comment]
I guess Edsger Wybe Dijkstra should have work on support, for he would have
enjoyed cases closing themselves ! ;-)
